#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""JIANT FM UI art -> firmware/src/ui_art_data.h

Each 240x240 PNG in art/ becomes: a 16-colour palette (RGB565, byte-swapped for the ST7789 like
gfx.c swap16), 4 bits per pixel (high nibble = even x), raw-deflate compressed (ui_art.c inflates it).

    python3 tools/gen_ui_art.py art/ firmware/src/ui_art_data.h [--dump out_dir]

--dump also writes, per screen, the expected byte-swapped RGB565 frame (for test/host_test.c).
Requires Pillow. Art must be exactly 240x240; order = file name order (01_home.png, 02_track.png ...).
"""
import sys, zlib, pathlib, re
from PIL import Image
import numpy as np

W = H = 240
NCOL = 16

def rgb565_swapped(r, g, b):
    v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    return ((v >> 8) & 0xFF) | ((v & 0xFF) << 8)

def palette16(im):
    """8 colours for the neutral line work, 8 for the coloured accents (a plain median cut of the whole
    image spends everything on the cream and drops the small coral, teal and yellow strokes)."""
    a = np.asarray(im).reshape(-1, 3).astype(np.float32)
    mx, mn = a.max(1), a.min(1)
    sat = (mx - mn) / np.maximum(mx, 1)
    colourful = (sat > .32) & (mx > 70)
    def cut(px, n):
        if len(px) < n:
            px = np.vstack([px, np.zeros((n, 3), np.float32)])
        img = Image.fromarray(px.reshape(1, -1, 3).astype(np.uint8))
        q = img.quantize(n, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
        p = q.getpalette()[:n * 3]
        p += [0] * (n * 3 - len(p))
        return [tuple(p[i * 3:i * 3 + 3]) for i in range(n)]
    pal = cut(a[~colourful], 8) + cut(a[colourful], 8)
    P_ = np.array(pal, np.float32)
    w = np.array([.30, .59, .11], np.float32) * 3
    d = (((a[:, None, :] - P_[None, :, :]) ** 2) * w).sum(2)
    return pal, d.argmin(1).tolist()

def convert(path):
    im = Image.open(path).convert("RGB")
    if im.size != (W, H):
        raise SystemExit(f"{path}: {im.size}, expected 240x240")
    pal, idx = palette16(im)
    order = sorted(range(NCOL), key=lambda i: sum(pal[i]))          # darkest first: index 0 = background
    remap = {old: new for new, old in enumerate(order)}
    idx = [remap[p] for p in idx]
    pal = [c for o in order for c in pal[o]]
    pal565 = [rgb565_swapped(*pal[i * 3:i * 3 + 3]) for i in range(NCOL)]
    packed = bytes((idx[i] << 4) | idx[i + 1] for i in range(0, W * H, 2))
    co = zlib.compressobj(9, zlib.DEFLATED, -15, 9)
    z = co.compress(packed) + co.flush()
    frame = b"".join(pal565[i].to_bytes(2, "little") for i in idx)  # what cv_px holds, in memory order
    return pal565, z, frame

def cname(stem):
    s = re.sub(r"^\d+[_-]?", "", stem).upper()
    return "UA_" + re.sub(r"[^A-Z0-9]+", "_", s).strip("_")

def main():
    a = sys.argv[1:]
    dump = None
    if "--dump" in a:
        i = a.index("--dump"); dump = pathlib.Path(a[i + 1]); del a[i:i + 2]
    src, out = pathlib.Path(a[0]), pathlib.Path(a[1])
    files = sorted(src.glob("*.png"))
    lines = ["/* SPDX-License-Identifier: GPL-3.0-only */",
             "/* JIANT FM UI art: generated by tools/gen_ui_art.py from the art PNGs. Do not edit. */",
             f"#define UI_ART_N {len(files)}u", f"#define UI_ART_W {W}u", f"#define UI_ART_H {H}u", "",
             "enum {"]
    lines += [f"    {cname(f.stem)} = {i}," for i, f in enumerate(files)]
    lines += ["};", "",
              "typedef struct {",
              "    const char *name;",
              "    uint16_t pal[16];        /* RGB565, byte-swapped (as cv_px holds it) */",
              "    uint32_t zlen;           /* raw deflate size */",
              "    const uint8_t *z;        /* 240 x 240 x 4 bit, high nibble = even x */",
              "} ui_art_t;", ""]
    total = 0
    if dump: dump.mkdir(parents=True, exist_ok=True)
    for i, f in enumerate(files):
        pal, z, frame = convert(f)
        total += len(z)
        if dump: (dump / f"{i:02d}.bin").write_bytes(frame)
        lines.append(f"static const uint8_t ua_z{i:02d}[{len(z)}] = {{")
        for k in range(0, len(z), 24):
            lines.append("    " + ",".join(f"0x{b:02x}" for b in z[k:k + 24]) + ",")
        lines.append("};")
        globals().setdefault("_meta", []).append((f.stem, pal, len(z), i))
    lines.append("")
    lines.append("static const ui_art_t ui_art[UI_ART_N] = {")
    for stem, pal, zl, i in _meta:
        lines.append(f'    {{"{cname(stem)[3:]}", {{{", ".join(f"0x{p:04x}" for p in pal)}}}, {zl}u, ua_z{i:02d}}},')
    lines.append("};")
    lines.append(f"/* total compressed art: {total} bytes */")
    out.write_text("\n".join(lines) + "\n")
    print(f"{len(files)} screens, {total} bytes compressed -> {out}")

if __name__ == "__main__":
    main()
