#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""JIANT FM's line art: SVG paths -> ui_shapes.h (run by tools/build.py generate()).

  gen_ui_shapes.py OUT.h [SVG_DIR]          (default: assets/ui-shapes)

Every SVG in SVG_DIR is a screen; every <path> with an id in it is a shape. Conventions (docs/TONIC-UI.md):
  - the canvas is viewBox="-64 -64 128 128": one unit is one stored step (int8), the origin the shape's anchor on
    screen (the firmware places, scales and mirrors it; y grows downwards as in SVG)
  - a shape that morphs is two paths, NAME_a and NAME_b, with the same number of segments (the firmware moves every
    point from A to B); a path without _a / _b does not morph
  - data-mirror="1" on a path (or its _a): the firmware also draws it mirrored left-right (one half of a symmetric
    organ, or the right one of a pair)
  - one subpath per path: M, then C S Q T L H V (absolute or relative), Z. Lines and quadratics become cubics.
    A closed path (Z) ends where it started
Out: per shape, static const int8_t SH_<SCREEN>_<NAME>_PTS[2][n] (A then B: a start point, three points a cubic
segment) and static const og_shape_t SH_<SCREEN>_<NAME> = {segments, mirror, A, B}.
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

TOK = re.compile(r"[MmCcSsQqTtLlHhVvZz]|-?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?")


def cubics(d):
    """path data -> start point, list of cubic segments ((x1, y1), (x2, y2), (x, y))"""
    toks = TOK.findall(d)
    i, cmd, cur, start, segs, last_c, last_q = 0, None, (0.0, 0.0), None, [], None, None

    def num():
        nonlocal i
        v = float(toks[i])
        i += 1
        return v

    while i < len(toks):
        if re.match(r"[A-Za-z]", toks[i]):
            cmd = toks[i]
            i += 1
            if cmd in "Zz":
                if start and (abs(cur[0] - start[0]) > 1e-6 or abs(cur[1] - start[1]) > 1e-6):
                    a, b = cur, start
                    segs.append(((a[0] + (b[0] - a[0]) / 3, a[1] + (b[1] - a[1]) / 3),
                                 (a[0] + 2 * (b[0] - a[0]) / 3, a[1] + 2 * (b[1] - a[1]) / 3), b))
                cur = start
                last_c = last_q = None
                continue
        rel = cmd.islower()
        c = cmd.upper()
        ox, oy = cur if rel else (0.0, 0.0)
        if c == "M":
            if start is not None:
                raise ValueError("one subpath per path")
            cur = (ox + num(), oy + num())
            start = cur
            cmd = "l" if rel else "L"                    # (more pairs after M are lines)
            last_c = last_q = None
            continue
        if c in "LHV":
            if c == "L":
                p = (ox + num(), oy + num())
            elif c == "H":
                p = (ox + num() if rel else num(), cur[1])
            else:
                p = (cur[0], oy + num() if rel else num())
            a = cur
            segs.append(((a[0] + (p[0] - a[0]) / 3, a[1] + (p[1] - a[1]) / 3),
                         (a[0] + 2 * (p[0] - a[0]) / 3, a[1] + 2 * (p[1] - a[1]) / 3), p))
            cur, last_c, last_q = p, None, None
        elif c in "CS":
            if c == "C":
                p1 = (ox + num(), oy + num())
            else:
                p1 = (2 * cur[0] - last_c[0], 2 * cur[1] - last_c[1]) if last_c else cur
            p2 = (ox + num(), oy + num())
            p = (ox + num(), oy + num())
            segs.append((p1, p2, p))
            cur, last_c, last_q = p, p2, None
        elif c in "QT":
            if c == "Q":
                q = (ox + num(), oy + num())
            else:
                q = (2 * cur[0] - last_q[0], 2 * cur[1] - last_q[1]) if last_q else cur
            p = (ox + num(), oy + num())
            a = cur
            segs.append(((a[0] + 2 * (q[0] - a[0]) / 3, a[1] + 2 * (q[1] - a[1]) / 3),
                         (p[0] + 2 * (q[0] - p[0]) / 3, p[1] + 2 * (q[1] - p[1]) / 3), p))
            cur, last_c, last_q = p, None, q
        else:
            raise ValueError(f"unsupported path command {cmd}")
    if start is None or not segs:
        raise ValueError("empty path")
    return start, segs


def flat(start, segs):
    out = [start] + [p for s in segs for p in s]
    vals = []
    for x, y in out:
        for v in (x, y):
            r = int(round(v))
            if not -128 <= r <= 127:
                raise ValueError(f"point {v} outside the int8 canvas (-64..64 recommended)")
            vals.append(r)
    return vals


def main():
    out = Path(sys.argv[1])
    src = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / "assets" / "ui-shapes"
    lines = ["/* JIANT FM's line art: generated by tools/gen_ui_shapes.py from the SVGs in assets/ui-shapes. Do not edit:",
             " * edit the SVGs (docs/TONIC-UI.md). og_shape_t is ui_organic.c's. */"]
    total = 0
    for svg in sorted(src.glob("*.svg")):
        screen = re.sub(r"\W", "_", svg.stem).upper()
        paths = {}
        for el in ET.parse(svg).iter():
            if el.tag.split("}")[-1] == "path" and el.get("id"):
                paths[el.get("id")] = el
        names = []
        for pid in paths:
            base = pid[:-2] if pid.endswith(("_a", "_b")) else pid
            if base not in names:
                names.append(base)
        for base in names:
            a = paths.get(base + "_a", paths.get(base))
            b = paths.get(base + "_b", a)
            if a is None:
                raise SystemExit(f"{svg.name}: {base}_b without {base}_a")
            try:
                sa, ga = cubics(a.get("d"))
                sb, gb = cubics(b.get("d"))
                if len(ga) != len(gb):
                    raise ValueError(f"A has {len(ga)} segments, B {len(gb)}: they must match")
                va, vb = flat(sa, ga), flat(sb, gb)
            except ValueError as e:
                raise SystemExit(f"{svg.name}: {base}: {e}")
            name = "SH_" + screen + "_" + re.sub(r"\W", "_", base).upper()
            mirror = 1 if a.get("data-mirror") == "1" else 0
            lines.append(f"static const int8_t {name}_PTS[2][{len(va)}] = {{")
            lines.append("    {" + ", ".join(map(str, va)) + "},")
            lines.append("    {" + ", ".join(map(str, vb)) + "},")
            lines.append("};")
            lines.append(f"static const og_shape_t {name} = {{{len(ga)}, {mirror}, {name}_PTS[0], {name}_PTS[1]}};")
            total += 2 * len(va)
    lines.append(f"/* {total} bytes of points */")
    out.write_text("\n".join(lines) + "\n")
    print(f"gen_ui_shapes: {out} ({total} bytes of points)")


if __name__ == "__main__":
    main()
